const prmvacio = {
    autoriza: null,
    boletin:null,
    cantidad_minima:null,
    compra_minima:null,
    con_pag:null,
    created_at: "",
    cte: null,
    desProm:"",
    fec_fin: "",
    fec_ini: "",
    folio_ac: "",
    hra_fin: "",
    hra_ini: "",
    id: "",
    inc_similares: "",
    mostrador: null,
    numProm: null,
    paga: "",
    proveedor: "",
    retail: "",
    seg_0: null,
    seg_1: null,
    seg_2: null,
    seg_3: null,
    seg_4: null,
    status: "",
    tpoProm: "",
    u_alt: "",
    uds_limite: null,
    uds_por_cte: null,
    uds_vendidas: null,
    updated_at: ""
  }
  export {prmvacio}